[versions]
kotlin = "1.9.10"

[libraries]
colormath = "com.github.ajalt.colormath:colormath:3.3.2"
markdown = "org.jetbrains:markdown:0.5.0"
jna-core = "net.java.dev.jna:jna:5.13.0"

# used in tests
kotest =  "io.kotest:kotest-assertions-core:5.6.2"
systemrules = "com.github.stefanbirkner:system-rules:1.19.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = "org.jetbrains.dokka:1.8.20"
publish = "com.vanniktech.maven.publish:0.25.3"
