name: Publish

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'samples/**'
      - '*.md'
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest,  windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            NATIVE_TEST_TASK: :mordant:linkDebugTestMacosArm64 :mordant:macosX64Test
          - os: windows-latest
            NATIVE_TEST_TASK: :mordant:mingwX64Test
          - os: ubuntu-latest
            NATIVE_TEST_TASK: :mordant:linuxX64Test :mordant:linuxX64BackgroundTest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Cache Kotlin Native Compiler
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-konan-
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: :mordant:jvmTest :mordant:jsTest ${{matrix.NATIVE_TEST_TASK}} --stacktrace
      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip
      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip
  publish-all-targets:
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch git tags
        run: git fetch origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Deploy to sonatype
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :mordant:publish -PinferVersion=true

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.project.kotlin.incremental.multiplatform=false -Dorg.gradle.project.kotlin.native.disableCompilerDaemon=true -Dorg.gradle.jvmargs="-Xmx5g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
  ORG_GRADLE_PROJECT_SONATYPE_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_USERNAME }}
  ORG_GRADLE_PROJECT_SONATYPE_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_PASSWORD }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
